# Generated by Django 5.1.2 on 2024-10-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="seats_reserved",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
