# Generated by Django 5.1.2 on 2024-10-27 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_app", "0002_remove_event_booked_seats_event_is_booked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="capacity",
        ),
    ]
